//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIP_Omniture.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api3.omniture.com/admin/1.4/rest/?method=Report.Queue")]
        public string CreateReportEndpoint {
            get {
                return ((string)(this["CreateReportEndpoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X-WSSE: UsernameToken Username=\"jeff.herz:Novartis Pharma AG\", PasswordDigest=\"Dt" +
            "3sCPjFCjyXCij1/Q+tuxyccMQ=\", Nonce=\"ZWFmZTU0MTIzOGNiZjhiZjQ1MTg3NjZk\", Created=\"" +
            "2015-08-13T20:43:29Z\"")]
        public string CreateReportRequest {
            get {
                return ((string)(this["CreateReportRequest"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jeff.herz:Novartis Pharma AG")]
        public string USERNAME {
            get {
                return ((string)(this["USERNAME"]));
            }
            set {
                this["USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0996c7669837c54a5f3e6590e926279b")]
        public string SECRET {
            get {
                return ((string)(this["SECRET"]));
            }
            set {
                this["SECRET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api3.omniture.com/admin/1.4/rest/")]
        public string ENDPOINT {
            get {
                return ((string)(this["ENDPOINT"]));
            }
            set {
                this["ENDPOINT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kip-awareness.cnnxpazukb57.eu-west-1.rds.amazonaws.com;Initial Catalo" +
            "g=World_Data;User ID=Awareness;Password=AwarenessPassword")]
        public string World_DataConnectionString {
            get {
                return ((string)(this["World_DataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kip-awareness.cnnxpazukb57.eu-west-1.rds.amazonaws.com;Initial Catalo" +
            "g=Awareness_Map;Persist Security Info=True;User ID=Awareness;Password=AwarenessP" +
            "assword")]
        public string Awareness_MapConnectionString {
            get {
                return ((string)(this["Awareness_MapConnectionString"]));
            }
        }
    }
}
