#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIP_Omniture
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Awareness_Map")]
	public partial class AwarenessDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGeo_Total(Geo_Total instance);
    partial void UpdateGeo_Total(Geo_Total instance);
    partial void DeleteGeo_Total(Geo_Total instance);
    partial void Insertomniture_raw_count(omniture_raw_count instance);
    partial void Updateomniture_raw_count(omniture_raw_count instance);
    partial void Deleteomniture_raw_count(omniture_raw_count instance);
    #endregion
		
		public AwarenessDataClassesDataContext() : 
				base(global::KIP_Omniture.Properties.Settings.Default.Awareness_MapConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AwarenessDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwarenessDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwarenessDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AwarenessDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Geo_Total> Geo_Totals
		{
			get
			{
				return this.GetTable<Geo_Total>();
			}
		}
		
		public System.Data.Linq.Table<omniture_count> omniture_counts
		{
			get
			{
				return this.GetTable<omniture_count>();
			}
		}
		
		public System.Data.Linq.Table<omniture_raw_count> omniture_raw_counts
		{
			get
			{
				return this.GetTable<omniture_raw_count>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Geo_Totals")]
	public partial class Geo_Total : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Geo_Country;
		
		private string _Geo_City;
		
		private string _Geo_Region;
		
		private System.Nullable<decimal> _Geo_Capital_Latitude;
		
		private System.Nullable<decimal> _Geo_Capital_Longitude;
		
		private System.Nullable<long> _FaceBook;
		
		private System.Nullable<long> _Twitter;
		
		private System.Nullable<long> _YouTube;
		
		private System.Nullable<long> _Omniture;
		
		private System.Nullable<long> _Heartbeat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGeo_CountryChanging(string value);
    partial void OnGeo_CountryChanged();
    partial void OnGeo_CityChanging(string value);
    partial void OnGeo_CityChanged();
    partial void OnGeo_RegionChanging(string value);
    partial void OnGeo_RegionChanged();
    partial void OnGeo_Capital_LatitudeChanging(System.Nullable<decimal> value);
    partial void OnGeo_Capital_LatitudeChanged();
    partial void OnGeo_Capital_LongitudeChanging(System.Nullable<decimal> value);
    partial void OnGeo_Capital_LongitudeChanged();
    partial void OnFaceBookChanging(System.Nullable<long> value);
    partial void OnFaceBookChanged();
    partial void OnTwitterChanging(System.Nullable<long> value);
    partial void OnTwitterChanged();
    partial void OnYouTubeChanging(System.Nullable<long> value);
    partial void OnYouTubeChanged();
    partial void OnOmnitureChanging(System.Nullable<long> value);
    partial void OnOmnitureChanged();
    partial void OnHeartbeatChanging(System.Nullable<long> value);
    partial void OnHeartbeatChanged();
    #endregion
		
		public Geo_Total()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Country", DbType="NVarChar(100)")]
		public string Geo_Country
		{
			get
			{
				return this._Geo_Country;
			}
			set
			{
				if ((this._Geo_Country != value))
				{
					this.OnGeo_CountryChanging(value);
					this.SendPropertyChanging();
					this._Geo_Country = value;
					this.SendPropertyChanged("Geo_Country");
					this.OnGeo_CountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_City", DbType="NVarChar(100)")]
		public string Geo_City
		{
			get
			{
				return this._Geo_City;
			}
			set
			{
				if ((this._Geo_City != value))
				{
					this.OnGeo_CityChanging(value);
					this.SendPropertyChanging();
					this._Geo_City = value;
					this.SendPropertyChanged("Geo_City");
					this.OnGeo_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Region", DbType="NVarChar(100)")]
		public string Geo_Region
		{
			get
			{
				return this._Geo_Region;
			}
			set
			{
				if ((this._Geo_Region != value))
				{
					this.OnGeo_RegionChanging(value);
					this.SendPropertyChanging();
					this._Geo_Region = value;
					this.SendPropertyChanged("Geo_Region");
					this.OnGeo_RegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Capital_Latitude", DbType="Decimal(12,8)")]
		public System.Nullable<decimal> Geo_Capital_Latitude
		{
			get
			{
				return this._Geo_Capital_Latitude;
			}
			set
			{
				if ((this._Geo_Capital_Latitude != value))
				{
					this.OnGeo_Capital_LatitudeChanging(value);
					this.SendPropertyChanging();
					this._Geo_Capital_Latitude = value;
					this.SendPropertyChanged("Geo_Capital_Latitude");
					this.OnGeo_Capital_LatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Capital_Longitude", DbType="Decimal(12,8)")]
		public System.Nullable<decimal> Geo_Capital_Longitude
		{
			get
			{
				return this._Geo_Capital_Longitude;
			}
			set
			{
				if ((this._Geo_Capital_Longitude != value))
				{
					this.OnGeo_Capital_LongitudeChanging(value);
					this.SendPropertyChanging();
					this._Geo_Capital_Longitude = value;
					this.SendPropertyChanged("Geo_Capital_Longitude");
					this.OnGeo_Capital_LongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceBook", DbType="BigInt")]
		public System.Nullable<long> FaceBook
		{
			get
			{
				return this._FaceBook;
			}
			set
			{
				if ((this._FaceBook != value))
				{
					this.OnFaceBookChanging(value);
					this.SendPropertyChanging();
					this._FaceBook = value;
					this.SendPropertyChanged("FaceBook");
					this.OnFaceBookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Twitter", DbType="BigInt")]
		public System.Nullable<long> Twitter
		{
			get
			{
				return this._Twitter;
			}
			set
			{
				if ((this._Twitter != value))
				{
					this.OnTwitterChanging(value);
					this.SendPropertyChanging();
					this._Twitter = value;
					this.SendPropertyChanged("Twitter");
					this.OnTwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YouTube", DbType="BigInt")]
		public System.Nullable<long> YouTube
		{
			get
			{
				return this._YouTube;
			}
			set
			{
				if ((this._YouTube != value))
				{
					this.OnYouTubeChanging(value);
					this.SendPropertyChanging();
					this._YouTube = value;
					this.SendPropertyChanged("YouTube");
					this.OnYouTubeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Omniture", DbType="BigInt")]
		public System.Nullable<long> Omniture
		{
			get
			{
				return this._Omniture;
			}
			set
			{
				if ((this._Omniture != value))
				{
					this.OnOmnitureChanging(value);
					this.SendPropertyChanging();
					this._Omniture = value;
					this.SendPropertyChanged("Omniture");
					this.OnOmnitureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heartbeat", DbType="BigInt")]
		public System.Nullable<long> Heartbeat
		{
			get
			{
				return this._Heartbeat;
			}
			set
			{
				if ((this._Heartbeat != value))
				{
					this.OnHeartbeatChanging(value);
					this.SendPropertyChanging();
					this._Heartbeat = value;
					this.SendPropertyChanged("Heartbeat");
					this.OnHeartbeatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.omniture_counts")]
	public partial class omniture_count
	{
		
		private System.Nullable<int> _Count;
		
		private string _Geo_Country;
		
		public omniture_count()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Int")]
		public System.Nullable<int> Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this._Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Country", DbType="NVarChar(100)")]
		public string Geo_Country
		{
			get
			{
				return this._Geo_Country;
			}
			set
			{
				if ((this._Geo_Country != value))
				{
					this._Geo_Country = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.omniture_raw_counts")]
	public partial class omniture_raw_count : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _City;
		
		private string _Country;
		
		private string _Region;
		
		private System.Nullable<int> _pageViews;
		
		private System.Nullable<int> _visits;
		
		private System.Nullable<int> _uniquevisitors;
		
		private System.Nullable<decimal> _latitude;
		
		private System.Nullable<decimal> _longitude;
		
		private string _Geo_City;
		
		private string _Geo_Country;
		
		private string _Geo_Region;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnpageViewsChanging(System.Nullable<int> value);
    partial void OnpageViewsChanged();
    partial void OnvisitsChanging(System.Nullable<int> value);
    partial void OnvisitsChanged();
    partial void OnuniquevisitorsChanging(System.Nullable<int> value);
    partial void OnuniquevisitorsChanged();
    partial void OnlatitudeChanging(System.Nullable<decimal> value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(System.Nullable<decimal> value);
    partial void OnlongitudeChanged();
    partial void OnGeo_CityChanging(string value);
    partial void OnGeo_CityChanged();
    partial void OnGeo_CountryChanging(string value);
    partial void OnGeo_CountryChanged();
    partial void OnGeo_RegionChanging(string value);
    partial void OnGeo_RegionChanged();
    #endregion
		
		public omniture_raw_count()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(100)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(100)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageViews", DbType="Int")]
		public System.Nullable<int> pageViews
		{
			get
			{
				return this._pageViews;
			}
			set
			{
				if ((this._pageViews != value))
				{
					this.OnpageViewsChanging(value);
					this.SendPropertyChanging();
					this._pageViews = value;
					this.SendPropertyChanged("pageViews");
					this.OnpageViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visits", DbType="Int")]
		public System.Nullable<int> visits
		{
			get
			{
				return this._visits;
			}
			set
			{
				if ((this._visits != value))
				{
					this.OnvisitsChanging(value);
					this.SendPropertyChanging();
					this._visits = value;
					this.SendPropertyChanged("visits");
					this.OnvisitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uniquevisitors", DbType="Int")]
		public System.Nullable<int> uniquevisitors
		{
			get
			{
				return this._uniquevisitors;
			}
			set
			{
				if ((this._uniquevisitors != value))
				{
					this.OnuniquevisitorsChanging(value);
					this.SendPropertyChanging();
					this._uniquevisitors = value;
					this.SendPropertyChanged("uniquevisitors");
					this.OnuniquevisitorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_City", DbType="NVarChar(100)")]
		public string Geo_City
		{
			get
			{
				return this._Geo_City;
			}
			set
			{
				if ((this._Geo_City != value))
				{
					this.OnGeo_CityChanging(value);
					this.SendPropertyChanging();
					this._Geo_City = value;
					this.SendPropertyChanged("Geo_City");
					this.OnGeo_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Country", DbType="NVarChar(100)")]
		public string Geo_Country
		{
			get
			{
				return this._Geo_Country;
			}
			set
			{
				if ((this._Geo_Country != value))
				{
					this.OnGeo_CountryChanging(value);
					this.SendPropertyChanging();
					this._Geo_Country = value;
					this.SendPropertyChanged("Geo_Country");
					this.OnGeo_CountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geo_Region", DbType="NVarChar(100)")]
		public string Geo_Region
		{
			get
			{
				return this._Geo_Region;
			}
			set
			{
				if ((this._Geo_Region != value))
				{
					this.OnGeo_RegionChanging(value);
					this.SendPropertyChanging();
					this._Geo_Region = value;
					this.SendPropertyChanged("Geo_Region");
					this.OnGeo_RegionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
